language: node_js
node_js:
  - "0.10"
  - "0.8"
before_install:
 - sudo add-apt-repository -y ppa:texlive-backports/ppa
 - sudo apt-get update -qq
 - sudo apt-get install -qq texlive-xetex texlive-latex-recommended texlive-latex-extra texlive-generic-extra texlive-fonts-recommended texlive-fonts-extra fonts-hosny-amiri ttf-devanagari-fonts fonts-nafees fonts-smc texlive-lang-all latex-xcolor imagemagick librsvg2-bin unzip
